language: python
python:
    - "nightly"
    - 3.6
    - 3.5
    - 3.4
    - 2.7
sudo: false
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade --pre -e .[test] pytest-cov pytest-warnings codecov
script:
  - py.test --cov jupyter_client jupyter_client
after_success:
  - codecov
matrix:
    allow_failures:
        - python: nightly
