matrix:
  fast_finish: true

environment:
  matrix:
  - CONDA_PY: 37
    CONDA_INSTALL_LOCN: '"C:\\Miniconda36-x64"'

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\\Scripts\\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  - cmd: conda install -y python=3.7 pyzmq tornado nbformat nbconvert ipykernel pip 
  - cmd: pip install .[test]
  - cmd: pip install --upgrade jupyter_core  # latest core not on conda yet

test_script:
  - pytest -v jupyter_kernel_mgmt/tests
